[package]
name = "notion-cli-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
dotenv = "0.15.0"
notion-client = "1.0.3"
serde_json = "1.0.128"
tokio = { version = "1", features = ["full"] }
